use_sim_time: false
a1_hardware_power_level: 9
stance_leg_control_type: 1 # 0: QP; 1: MPC

# physics parameters

a1_robot_mass: 12.5

a1_trunk_inertia_xx: 0.0178533
a1_trunk_inertia_xy: 0.0
a1_trunk_inertia_xz: 0.0
a1_trunk_inertia_yz: 0.0
a1_trunk_inertia_yy: 0.0377999
a1_trunk_inertia_zz: 0.0456542

# default foothold position

a1_default_foot_pos_FL_x: 0.17
a1_default_foot_pos_FL_y: 0.12
a1_default_foot_pos_FL_z: -0.32

a1_default_foot_pos_FR_x: 0.17
a1_default_foot_pos_FR_y: -0.12
a1_default_foot_pos_FR_z: -0.32

a1_default_foot_pos_RL_x: -0.17
a1_default_foot_pos_RL_y: 0.12
a1_default_foot_pos_RL_z: -0.32

a1_default_foot_pos_RR_x: -0.17
a1_default_foot_pos_RR_y: -0.12
a1_default_foot_pos_RR_z: -0.32

a1_gait_counter_speed_FL: 0.55
a1_gait_counter_speed_FR: 0.55
a1_gait_counter_speed_RL: 0.55
a1_gait_counter_speed_RR: 0.55

# MPC parameters

q_weights_0: 10.0 # roll 60
q_weights_1: 20.0 # pitch 80
q_weights_2: 60.0 # yaw

q_weights_3: 0 # pos x
q_weights_4: 0 # pos y
q_weights_5: 50 # pos z

q_weights_6: 0.02 # omega x
q_weights_7: 0.02 # omega y
q_weights_8: 10.0 # omega z

q_weights_9: 5 # vel x
q_weights_10: 5 # vel y
q_weights_11: 1 # vel z


q_weights_12: 0.0

r_weights_0: 0.000011
r_weights_1: 0.000011
r_weights_2: 0.000011

r_weights_3: 0.000011
r_weights_4: 0.000011
r_weights_5: 0.000011

r_weights_6: 0.000011
r_weights_7: 0.000011
r_weights_8: 0.000011

r_weights_9: 0.000011
r_weights_10: 0.000011
r_weights_11: 0.000011

# foot swing controller parameters
# force_tgt = km_foot * kp_foot * foot_pos_error

a1_kp_foot_x: 40.0
a1_kp_foot_y: 40.0
a1_kp_foot_z: 30.0

a1_kd_foot_x: 2.0
a1_kd_foot_y: 2.0
a1_kd_foot_z: 2.0

a1_km_foot_x: 0.1
a1_km_foot_y: 0.1
a1_km_foot_z: 0.1