package_dir: /home/zerenluo/unitree_ros_ws/src/Go1-QP-MPC-Controller/src/go1_rl_ctrl_cpp

use_sim_time: false # gazebo: true; hardware: false

stand_weights: stand_cpp_model.pt

weights: mass.pt

action_update_frequency: 2.5 # ms; 400 Hz

deployment_frequency: 1.0 # ms; 1000 Hz

go1_hardware_power_level: 6


