package_dir: /home/zerenluo/unitree_ros_ws/src/Go1-QP-MPC-Controller/src/go1_rl_ctrl_cpp

use_sim_time: true # gazebo: true; hardware: false

stand_weights: stand_cpp_model.pt

weights: cpp_model.pt

action_update_frequency: 0.1 # ms

deployment_frequency: 0.5 # ms


go1_robot_mass: 12.0

# default foothold position

go1_default_foot_pos_FL_x: 0.17
go1_default_foot_pos_FL_y: 0.15
go1_default_foot_pos_FL_z: -0.35

go1_default_foot_pos_FR_x: 0.17
go1_default_foot_pos_FR_y: -0.15
go1_default_foot_pos_FR_z: -0.35

go1_default_foot_pos_RL_x: -0.17
go1_default_foot_pos_RL_y: 0.15
go1_default_foot_pos_RL_z: -0.35

go1_default_foot_pos_RR_x: -0.17
go1_default_foot_pos_RR_y: -0.15
go1_default_foot_pos_RR_z: -0.35

go1_gait_counter_speed_FL: 0.7
go1_gait_counter_speed_FR: 0.7
go1_gait_counter_speed_RL: 0.7
go1_gait_counter_speed_RR: 0.7

# foot swing controller parameters
# force_tgt = km_foot * kp_foot * foot_pos_error

go1_kp_foot_x: 200.0
go1_kp_foot_y: 300.0
go1_kp_foot_z: 200.0

go1_kd_foot_x: 4.0
go1_kd_foot_y: 4.0
go1_kd_foot_z: 4.0

go1_km_foot_x: 0.1
go1_km_foot_y: 0.1
go1_km_foot_z: 0.1

# foot stance force controller parameters
# root_acc = [root_ddot_p_deisre; root_ddot_w_desire]
#   root_ddot_p_deisre = kp_linear (pos error)
#                        + kd_linear (linear velocity error)
#   root_ddot_w_desire = kp_angular (euler error)
#                        + kd_linear (rotation velocity error)
# root_acc are used to compute ground contact force

go1_kp_linear_x: 100.0
go1_kp_linear_y: 100.0
go1_kp_linear_z: 300.0

go1_kd_linear_x: 70.0
go1_kd_linear_y: 70.0
go1_kd_linear_z: 120.0

go1_kp_angular_x: 150.0
go1_kp_angular_y: 150.0
go1_kp_angular_z: 1.0

go1_kd_angular_x: 4.5
go1_kd_angular_y: 4.5
go1_kd_angular_z: 30.0

