package_dir: /home/zerenluo/unitree_ros_ws/src/Go1-RL-Controller/src/go1_rl_ctrl_cpp

use_sim_time: true # gazebo: true; hardware: false

robot_name: go1

stand_weights: stand_cpp_model.pt

weights: mass.pt

action_update_frequency: 4.0 # ms

deployment_frequency: 2.0 # ms

stiffness: 18.0 # 18.0 for 0.0002 and 5000

damping: 10.0 # 10.0 for 0.0002 and 5000